In [1]:
import numpy as np
import pandas as pd
from datetime import datetime

In [2]:
data = pd.read_csv("data/weather_data.csv", delimiter = ',')
data.head(10)

,month,date,min_temp,max_temp,sunrise,sunset,moonrise,moonset,wind_speed(km/h),wind_dir,rain(mm),humidity(%),cloud(%),pressure(mb),weather
0,1,1,12,18,06:33 AM,05:27 PM,09:38 AM,09:32 PM,6,NNE,0.0,69,41,1025,Cloudy
1,1,2,12,18,06:34 AM,05:28 PM,10:11 AM,10:23 PM,5,ESE,0.0,65,28,1025,Partly cloudy
2,1,3,12,20,06:34 AM,05:28 PM,10:44 AM,11:16 PM,5,ESE,0.0,75,41,1022,Cloudy
3,1,4,12,23,06:34 AM,05:29 PM,11:19 AM,No moonset,5,SSW,0.0,81,47,1018,Cloudy
4,1,5,14,23,06:35 AM,05:29 PM,11:56 AM,12:11 AM,5,SSE,0.1,90,77,1017,Patchy rain possible
5,1,6,15,23,06:35 AM,05:30 PM,12:38 PM,01:10 AM,5,E,2.9,88,73,1018,Patchy rain possible
6,1,7,13,16,06:35 AM,05:31 PM,01:27 PM,02:13 AM,9,NE,0.0,85,95,1023,Overcast
7,1,8,12,15,06:35 AM,05:31 PM,02:24 PM,03:20 AM,8,E,0.0,78,90,1026,Overcast
8,1,9,11,19,06:35 AM,05:32 PM,03:28 PM,04:28 AM,10,SE,0.0,60,21,1029,Partly cloudy
9,1,10,8,20,06:36 AM,05:33 PM,04:37 PM,05:34 AM,6,ENE,0.0,49,2,1027,Sunny

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5245 entries, 0 to 5244
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   month             5245 non-null   int64
 1   date              5245 non-null   int64
 2   min_temp          5245 non-null   int64
 3   max_temp          5245 non-null   int64
 4   sunrise           5245 non-null   object
 5   sunset            5245 non-null   object
 6   moonrise          5245 non-null   object
 7   moonset           5245 non-null   object
 8   wind_speed(km/h)  5245 non-null   int64
 9   wind_dir          5245 non-null   object
 10  rain(mm)          5245 non-null   float64
 11  humidity(%)       5245 non-null   int64
 12  cloud(%)          5245 non-null   int64
 13  pressure(mb)      5245 non-null   int64
 14  weather           5245 non-null   object
dtypes: float64(1), int64(8), object(6)
memory usage: 614.8+ KB

# Nhận xét
Dữ liệu không có trống nhưng ta kiểm tra xem có giá trị nào bằng 0.0 hay không

In [4]:
len(data[data['min_temp']== 0.0])

0

In [5]:
len(data[data['max_temp']== 0.0])

0

In [6]:
len(data[data['wind_speed(km/h)']== 0.0])

0

In [7]:
len(data[data['wind_dir']== 'NaN'])

0

In [8]:
len(data[data['pressure(mb)']== 0.0])

0

In [9]:
len(data[data['weather']== 'NaN'])

0

# Nhận xét
- Có một số dữ liệu là 0.0 nhưng hầu hết là hợp lý trừ trường hợp của "min_temp và max_temp" vì Hà Nội chưa bao giờ có nhiệt độ là 0 độ C.

# Xử lý dữ liệu

In [10]:
# Sao chép cột 'weather' vào cột mới 'current_weather'
data['current_weather'] = data['weather'].copy()

# Đổi vị trí cột 'current_weather' và cột 'weather'
data = data.reindex(columns=['month','date','min_temp','max_temp','sunrise','sunset','moonrise','moonset','wind_speed(km/h)','wind_dir','rain(mm)','humidity(%)','cloud(%)','pressure(mb)','current_weather', 'weather'])
data

,month,date,min_temp,max_temp,sunrise,sunset,moonrise,moonset,wind_speed(km/h),wind_dir,rain(mm),humidity(%),cloud(%),pressure(mb),current_weather,weather
0,1,1,12,18,06:33 AM,05:27 PM,09:38 AM,09:32 PM,6,NNE,0.0,69,41,1025,Cloudy,Cloudy
1,1,2,12,18,06:34 AM,05:28 PM,10:11 AM,10:23 PM,5,ESE,0.0,65,28,1025,Partly cloudy,Partly cloudy
2,1,3,12,20,06:34 AM,05:28 PM,10:44 AM,11:16 PM,5,ESE,0.0,75,41,1022,Cloudy,Cloudy
3,1,4,12,23,06:34 AM,05:29 PM,11:19 AM,No moonset,5,SSW,0.0,81,47,1018,Cloudy,Cloudy
4,1,5,14,23,06:35 AM,05:29 PM,11:56 AM,12:11 AM,5,SSE,0.1,90,77,1017,Patchy rain possible,Patchy rain possible
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5240,5,11,22,33,05:21 AM,06:25 PM,No moonrise,10:16 AM,14,ESE,25.6,80,77,1011,Moderate or heavy rain shower,Moderate or heavy rain shower
5241,5,12,20,22,05:21 AM,06:25 PM,12:09 AM,11:22 AM,12,WNW,28.9,91,100,1015,Moderate rain,Moderate rain
5242,5,13,22,24,05:20 AM,06:26 PM,12:56 AM,12:25 PM,9,NNW,0.7,89,98,1013,Patchy rain possible,Patchy rain possible
5243,5,14,22,27,05:20 AM,06:26 PM,01:38 AM,01:26 PM,12,NW,0.6,80,65,1012,Overcast,Overcast
5244,5,15,20,33,05:19 AM,06:27 PM,02:16 AM,02:24 PM,10,SW,0.0,73,40,1009,Cloudy,Cloudy

In [11]:
# Biến đổi giá trị của cột cuối cùng (nhãn) thành giá trị của dòng trước đó
data.iloc[:, -1] = data.iloc[:, -1].shift(-1)
data

,month,date,min_temp,max_temp,sunrise,sunset,moonrise,moonset,wind_speed(km/h),wind_dir,rain(mm),humidity(%),cloud(%),pressure(mb),current_weather,weather
0,1,1,12,18,06:33 AM,05:27 PM,09:38 AM,09:32 PM,6,NNE,0.0,69,41,1025,Cloudy,Partly cloudy
1,1,2,12,18,06:34 AM,05:28 PM,10:11 AM,10:23 PM,5,ESE,0.0,65,28,1025,Partly cloudy,Cloudy
2,1,3,12,20,06:34 AM,05:28 PM,10:44 AM,11:16 PM,5,ESE,0.0,75,41,1022,Cloudy,Cloudy
3,1,4,12,23,06:34 AM,05:29 PM,11:19 AM,No moonset,5,SSW,0.0,81,47,1018,Cloudy,Patchy rain possible
4,1,5,14,23,06:35 AM,05:29 PM,11:56 AM,12:11 AM,5,SSE,0.1,90,77,1017,Patchy rain possible,Patchy rain possible
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5240,5,11,22,33,05:21 AM,06:25 PM,No moonrise,10:16 AM,14,ESE,25.6,80,77,1011,Moderate or heavy rain shower,Moderate rain
5241,5,12,20,22,05:21 AM,06:25 PM,12:09 AM,11:22 AM,12,WNW,28.9,91,100,1015,Moderate rain,Patchy rain possible
5242,5,13,22,24,05:20 AM,06:26 PM,12:56 AM,12:25 PM,9,NNW,0.7,89,98,1013,Patchy rain possible,Overcast
5243,5,14,22,27,05:20 AM,06:26 PM,01:38 AM,01:26 PM,12,NW,0.6,80,65,1012,Overcast,Cloudy
5244,5,15,20,33,05:19 AM,06:27 PM,02:16 AM,02:24 PM,10,SW,0.0,73,40,1009,Cloudy,None

# Loại bỏ thuộc tính dư thừa
Ở đây chúng ta thấy cột time và date có thể loại bỏ vì giá trị của nó không có nhiều ảnh hưởng đến dự đoán thời tiết.

In [12]:
# data.drop('month', axis=1, inplace=True)
data.drop('date', axis=1, inplace=True)
data

,month,min_temp,max_temp,sunrise,sunset,moonrise,moonset,wind_speed(km/h),wind_dir,rain(mm),humidity(%),cloud(%),pressure(mb),current_weather,weather
0,1,12,18,06:33 AM,05:27 PM,09:38 AM,09:32 PM,6,NNE,0.0,69,41,1025,Cloudy,Partly cloudy
1,1,12,18,06:34 AM,05:28 PM,10:11 AM,10:23 PM,5,ESE,0.0,65,28,1025,Partly cloudy,Cloudy
2,1,12,20,06:34 AM,05:28 PM,10:44 AM,11:16 PM,5,ESE,0.0,75,41,1022,Cloudy,Cloudy
3,1,12,23,06:34 AM,05:29 PM,11:19 AM,No moonset,5,SSW,0.0,81,47,1018,Cloudy,Patchy rain possible
4,1,14,23,06:35 AM,05:29 PM,11:56 AM,12:11 AM,5,SSE,0.1,90,77,1017,Patchy rain possible,Patchy rain possible
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5240,5,22,33,05:21 AM,06:25 PM,No moonrise,10:16 AM,14,ESE,25.6,80,77,1011,Moderate or heavy rain shower,Moderate rain
5241,5,20,22,05:21 AM,06:25 PM,12:09 AM,11:22 AM,12,WNW,28.9,91,100,1015,Moderate rain,Patchy rain possible
5242,5,22,24,05:20 AM,06:26 PM,12:56 AM,12:25 PM,9,NNW,0.7,89,98,1013,Patchy rain possible,Overcast
5243,5,22,27,05:20 AM,06:26 PM,01:38 AM,01:26 PM,12,NW,0.6,80,65,1012,Overcast,Cloudy
5244,5,20,33,05:19 AM,06:27 PM,02:16 AM,02:24 PM,10,SW,0.0,73,40,1009,Cloudy,None

## Xoá hàng có giá trị None

In [13]:
data = data.dropna()
data

,month,min_temp,max_temp,sunrise,sunset,moonrise,moonset,wind_speed(km/h),wind_dir,rain(mm),humidity(%),cloud(%),pressure(mb),current_weather,weather
0,1,12,18,06:33 AM,05:27 PM,09:38 AM,09:32 PM,6,NNE,0.0,69,41,1025,Cloudy,Partly cloudy
1,1,12,18,06:34 AM,05:28 PM,10:11 AM,10:23 PM,5,ESE,0.0,65,28,1025,Partly cloudy,Cloudy
2,1,12,20,06:34 AM,05:28 PM,10:44 AM,11:16 PM,5,ESE,0.0,75,41,1022,Cloudy,Cloudy
3,1,12,23,06:34 AM,05:29 PM,11:19 AM,No moonset,5,SSW,0.0,81,47,1018,Cloudy,Patchy rain possible
4,1,14,23,06:35 AM,05:29 PM,11:56 AM,12:11 AM,5,SSE,0.1,90,77,1017,Patchy rain possible,Patchy rain possible
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5239,5,23,32,05:22 AM,06:25 PM,11:17 PM,09:11 AM,10,SE,54.7,87,88,1009,Torrential rain shower,Moderate or heavy rain shower
5240,5,22,33,05:21 AM,06:25 PM,No moonrise,10:16 AM,14,ESE,25.6,80,77,1011,Moderate or heavy rain shower,Moderate rain
5241,5,20,22,05:21 AM,06:25 PM,12:09 AM,11:22 AM,12,WNW,28.9,91,100,1015,Moderate rain,Patchy rain possible
5242,5,22,24,05:20 AM,06:26 PM,12:56 AM,12:25 PM,9,NNW,0.7,89,98,1013,Patchy rain possible,Overcast
5243,5,22,27,05:20 AM,06:26 PM,01:38 AM,01:26 PM,12,NW,0.6,80,65,1012,Overcast,Cloudy

# Xử lý dữ liệu

## Các giá trị thời gian

In [14]:
def convert_time_val(time_):
  if time_.split(' ')[0].strip() == 'No':
    return 0
  hour = datetime.strptime(time_, '%I:%M %p').time().hour
  mins = datetime.strptime(time_, '%I:%M %p').time().minute
  hour = hour + 1 if mins > 50 else hour
  return hour

### khảo sát giá trị sunrise

In [15]:
sunrise_value = data["sunrise"].unique()
sunrise_value

array(['06:33 AM', '06:34 AM', '06:35 AM', '06:36 AM', '06:32 AM',
       '06:31 AM', '06:30 AM', '06:29 AM', '06:28 AM', '06:27 AM',
       '06:26 AM', '06:25 AM', '06:24 AM', '06:23 AM', '06:22 AM',
       '06:21 AM', '06:20 AM', '06:19 AM', '06:18 AM', '06:17 AM',
       '06:16 AM', '06:15 AM', '06:14 AM', '06:13 AM', '06:12 AM',
       '06:11 AM', '06:10 AM', '06:09 AM', '06:08 AM', '06:07 AM',
       '06:06 AM', '06:05 AM', '06:04 AM', '06:03 AM', '06:02 AM',
       '06:01 AM', '06:00 AM', '05:59 AM', '05:58 AM', '05:57 AM',
       '05:56 AM', '05:55 AM', '05:54 AM', '05:53 AM', '05:52 AM',
       '05:51 AM', '05:50 AM', '05:49 AM', '05:48 AM', '05:47 AM',
       '05:46 AM', '05:45 AM', '05:44 AM', '05:43 AM', '05:42 AM',
       '05:41 AM', '05:40 AM', '05:39 AM', '05:38 AM', '05:37 AM',
       '05:36 AM', '05:35 AM', '05:34 AM', '05:33 AM', '05:32 AM',
       '05:31 AM', '05:30 AM', '05:29 AM', '05:28 AM', '05:27 AM',
       '05:26 AM', '05:25 AM', '05:24 AM', '05:23 AM', '05:22 AM',
       '05:21 AM', '05:20 AM', '05:19 AM', '05:18 AM', '05:17 AM',
       '05:16 AM', '05:15 AM'], dtype=object)

In [16]:
data['sunrise'] = data['sunrise'].apply(lambda x: convert_time_val(x))

C:\Users\Nomocp\AppData\Local\Temp\ipykernel_25024\3656327232.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['sunrise'] = data['sunrise'].apply(lambda x: convert_time_val(x))

### khảo sát giá trị sunset

In [17]:
sunset_value = data["sunset"].unique()
sunset_value

array(['05:27 PM', '05:28 PM', '05:29 PM', '05:30 PM', '05:31 PM',
       '05:32 PM', '05:33 PM', '05:34 PM', '05:35 PM', '05:36 PM',
       '05:37 PM', '05:38 PM', '05:39 PM', '05:40 PM', '05:41 PM',
       '05:42 PM', '05:43 PM', '05:44 PM', '05:45 PM', '05:46 PM',
       '05:47 PM', '05:48 PM', '05:49 PM', '05:50 PM', '05:51 PM',
       '05:52 PM', '05:53 PM', '05:54 PM', '05:55 PM', '05:56 PM',
       '05:57 PM', '05:58 PM', '05:59 PM', '06:00 PM', '06:01 PM',
       '06:02 PM', '06:03 PM', '06:04 PM', '06:05 PM', '06:06 PM',
       '06:07 PM', '06:08 PM', '06:09 PM', '06:10 PM', '06:11 PM',
       '06:12 PM', '06:13 PM', '06:14 PM', '06:15 PM', '06:16 PM',
       '06:17 PM', '06:18 PM', '06:19 PM', '06:20 PM', '06:21 PM',
       '06:22 PM', '06:23 PM', '06:24 PM', '06:25 PM', '06:26 PM',
       '06:27 PM', '06:28 PM', '06:29 PM', '06:30 PM', '06:31 PM',
       '06:32 PM', '06:33 PM', '06:34 PM', '06:35 PM', '06:36 PM',
       '06:37 PM', '06:38 PM', '06:39 PM', '06:40 PM', '06:41 PM',
       '06:42 PM', '05:26 PM', '05:25 PM', '05:24 PM', '05:23 PM',
       '05:22 PM', '05:21 PM', '05:20 PM', '05:19 PM', '05:18 PM',
       '05:17 PM', '05:16 PM', '05:15 PM', '05:14 PM'], dtype=object)

In [18]:
data['sunset'] = data['sunset'].apply(lambda x: convert_time_val(x))

C:\Users\Nomocp\AppData\Local\Temp\ipykernel_25024\3103169393.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['sunset'] = data['sunset'].apply(lambda x: convert_time_val(x))

### khảo sát giá trị moonrise

In [19]:
moonrise_value = data["moonrise"].unique()
moonrise_value

array(['09:38 AM', '10:11 AM', '10:44 AM', ..., '01:34 PM', '02:57 AM',
       '01:42 PM'], dtype=object)

In [20]:
data['moonrise'] = data['moonrise'].apply(lambda x: convert_time_val(x))

C:\Users\Nomocp\AppData\Local\Temp\ipykernel_25024\3995101652.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['moonrise'] = data['moonrise'].apply(lambda x: convert_time_val(x))

### khảo sát giá trị moonset

In [21]:
moonset_value = data["moonset"].unique()
moonrise_value

array(['09:38 AM', '10:11 AM', '10:44 AM', ..., '01:34 PM', '02:57 AM',
       '01:42 PM'], dtype=object)

In [22]:
data['moonset'] = data['moonset'].apply(lambda x: convert_time_val(x))

C:\Users\Nomocp\AppData\Local\Temp\ipykernel_25024\2894550051.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['moonset'] = data['moonset'].apply(lambda x: convert_time_val(x))

## Các giá trị dạng chữ cái

In [23]:
data

,month,min_temp,max_temp,sunrise,sunset,moonrise,moonset,wind_speed(km/h),wind_dir,rain(mm),humidity(%),cloud(%),pressure(mb),current_weather,weather
0,1,12,18,6,17,9,21,6,NNE,0.0,69,41,1025,Cloudy,Partly cloudy
1,1,12,18,6,17,10,22,5,ESE,0.0,65,28,1025,Partly cloudy,Cloudy
2,1,12,20,6,17,10,23,5,ESE,0.0,75,41,1022,Cloudy,Cloudy
3,1,12,23,6,17,11,0,5,SSW,0.0,81,47,1018,Cloudy,Patchy rain possible
4,1,14,23,6,17,12,0,5,SSE,0.1,90,77,1017,Patchy rain possible,Patchy rain possible
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5239,5,23,32,5,18,23,9,10,SE,54.7,87,88,1009,Torrential rain shower,Moderate or heavy rain shower
5240,5,22,33,5,18,0,10,14,ESE,25.6,80,77,1011,Moderate or heavy rain shower,Moderate rain
5241,5,20,22,5,18,0,11,12,WNW,28.9,91,100,1015,Moderate rain,Patchy rain possible
5242,5,22,24,5,18,1,12,9,NNW,0.7,89,98,1013,Patchy rain possible,Overcast
5243,5,22,27,5,18,1,13,12,NW,0.6,80,65,1012,Overcast,Cloudy

### khảo sát giá trị wind_dir

In [24]:
wind_dir_value = data["wind_dir"].unique()
wind_dir_value

array(['NNE', 'ESE', 'SSW', 'SSE', 'E', 'NE', 'SE', 'ENE', 'S', 'SW',
       'WSW', 'WNW', 'NW', 'W', 'NNW', 'N'], dtype=object)

In [25]:
direction_mapping = {
  'N': 0,
  'NNE': 22.5,
  'NE': 45,
  'ENE': 67.5,
  'E': 90,
  'ESE': 112.5,
  'SE': 135,
  'SSE': 157.5,
  'S': 180,
  'SSW': 202.5,
  'SW': 225,
  'WSW': 247.5,
  'W': 270,
  'WNW': 292.5,
  'NW': 315,
  'NNW': 337.5
}
# direction_mapping = {
#     'N': 1,
#     'NNE': 2,
#     'NE': 3,
#     'ENE': 4,
#     'E': 5,
#     'ESE': 6,
#     'SE': 7,
#     'SSE': 8,
#     'S': 9,
#     'SSW': 10,
#     'SW': 11,
#     'WSW': 12,
#     'W': 13,
#     'WNW': 14,
#     'NW': 15,
#     'NNW': 16
# }

# Áp dụng ánh xạ từ từ điển vào cột 'direction'
data['wind_dir'] = data['wind_dir'].map(direction_mapping)

C:\Users\Nomocp\AppData\Local\Temp\ipykernel_25024\2571349417.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['wind_dir'] = data['wind_dir'].map(direction_mapping)

In [26]:
data

,month,min_temp,max_temp,sunrise,sunset,moonrise,moonset,wind_speed(km/h),wind_dir,rain(mm),humidity(%),cloud(%),pressure(mb),current_weather,weather
0,1,12,18,6,17,9,21,6,22.5,0.0,69,41,1025,Cloudy,Partly cloudy
1,1,12,18,6,17,10,22,5,112.5,0.0,65,28,1025,Partly cloudy,Cloudy
2,1,12,20,6,17,10,23,5,112.5,0.0,75,41,1022,Cloudy,Cloudy
3,1,12,23,6,17,11,0,5,202.5,0.0,81,47,1018,Cloudy,Patchy rain possible
4,1,14,23,6,17,12,0,5,157.5,0.1,90,77,1017,Patchy rain possible,Patchy rain possible
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5239,5,23,32,5,18,23,9,10,135.0,54.7,87,88,1009,Torrential rain shower,Moderate or heavy rain shower
5240,5,22,33,5,18,0,10,14,112.5,25.6,80,77,1011,Moderate or heavy rain shower,Moderate rain
5241,5,20,22,5,18,0,11,12,292.5,28.9,91,100,1015,Moderate rain,Patchy rain possible
5242,5,22,24,5,18,1,12,9,337.5,0.7,89,98,1013,Patchy rain possible,Overcast
5243,5,22,27,5,18,1,13,12,315.0,0.6,80,65,1012,Overcast,Cloudy

### khảo sát giá trị nhãn

In [27]:
label_value = data["weather"].unique()
label_value

array(['Partly cloudy', 'Cloudy', 'Patchy rain possible', 'Overcast',
       'Sunny', 'Moderate rain at times', 'Moderate or heavy rain shower',
       'Heavy rain at times', 'Mist', 'Light rain shower', 'Light rain',
       'Light drizzle', 'Thundery outbreaks possible',
       'Torrential rain shower', 'Moderate rain'], dtype=object)

biến đổi

In [28]:
list_norain = ['Clear', 'Thundery outbreaks possible', 
                'Partly cloudy', 'Cloudy', 'Mist', 'Sunny']
list_rain = ['Light drizzle','Light rain','Light rain shower',
             'Patchy light drizzle', 'Patchy light rain', 
             'Patchy light rain with thunder','Patchy rain possible',
             'Heavy rain','Heavy rain at times', 'Overcast',
             'Moderate or heavy rain shower','Moderate rain',
             'Moderate rain at times','Torrential rain shower']

Thêm cột thời tiết mưa hoặc không mưa làm nhãn

In [29]:
data['weather'] = data['weather'].apply(lambda x: 0 if x in list_norain else 1)
data['current_weather'] = data['current_weather'].apply(lambda x: 0 if x in list_norain else 1)

C:\Users\Nomocp\AppData\Local\Temp\ipykernel_25024\3508015919.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['weather'] = data['weather'].apply(lambda x: 0 if x in list_norain else 1)
C:\Users\Nomocp\AppData\Local\Temp\ipykernel_25024\3508015919.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['current_weather'] = data['current_weather'].apply(lambda x: 0 if x in list_norain else 1)

In [30]:
data

,month,min_temp,max_temp,sunrise,sunset,moonrise,moonset,wind_speed(km/h),wind_dir,rain(mm),humidity(%),cloud(%),pressure(mb),current_weather,weather
0,1,12,18,6,17,9,21,6,22.5,0.0,69,41,1025,0,0
1,1,12,18,6,17,10,22,5,112.5,0.0,65,28,1025,0,0
2,1,12,20,6,17,10,23,5,112.5,0.0,75,41,1022,0,0
3,1,12,23,6,17,11,0,5,202.5,0.0,81,47,1018,0,1
4,1,14,23,6,17,12,0,5,157.5,0.1,90,77,1017,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5239,5,23,32,5,18,23,9,10,135.0,54.7,87,88,1009,1,1
5240,5,22,33,5,18,0,10,14,112.5,25.6,80,77,1011,1,1
5241,5,20,22,5,18,0,11,12,292.5,28.9,91,100,1015,1,1
5242,5,22,24,5,18,1,12,9,337.5,0.7,89,98,1013,1,1
5243,5,22,27,5,18,1,13,12,315.0,0.6,80,65,1012,1,0

In [31]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5244 entries, 0 to 5243
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   month             5244 non-null   int64
 1   min_temp          5244 non-null   int64
 2   max_temp          5244 non-null   int64
 3   sunrise           5244 non-null   int64
 4   sunset            5244 non-null   int64
 5   moonrise          5244 non-null   int64
 6   moonset           5244 non-null   int64
 7   wind_speed(km/h)  5244 non-null   int64
 8   wind_dir          5244 non-null   float64
 9   rain(mm)          5244 non-null   float64
 10  humidity(%)       5244 non-null   int64
 11  cloud(%)          5244 non-null   int64
 12  pressure(mb)      5244 non-null   int64
 13  current_weather   5244 non-null   int64
 14  weather           5244 non-null   int64
dtypes: float64(2), int64(13)
memory usage: 655.5 KB

In [32]:
# Lưu lại file đã xử lý tên: processed_weather_data.csv
data.to_csv("data/processed_weather_data.csv", index=False)